use bytes instead of int array for CCBV
c-cube/ocaml-containers pull request #376
Opened 2021-05-22 19:40 UTC by FardaleM

2021-05-22 20:11 UTC, c-cube requested changes
Excellent :woman_dancing: . Just a few changes but I think this will be super helpful.

2021-05-22 20:11 UTC, c-cube commented on src/data/CCBV.ml
> +      Bytes.unsafe_set b (n-1) (Bytes.unsafe_get lsb_masks_ r);
```suggestion
      Bytes.unsafe_set b (n-1) ((1 lsl r) - 1);
```

this should set `r` bits to one.

2021-05-22 20:11 UTC, c-cube commented on src/data/CCBV.ml
> +let __to_word_l bv = CCString.to_list (Bytes.unsafe_to_string bv.b)
```suggestion
let __to_word_l bv =
  let l = ref [] in
  Bytes.iter (fun c -> l := c :: !l) bv.b;
  List.rev !l
```

it's a bit sad to pull a dep on this module just for this one function :grin:

2021-05-23 00:06 UTC, favonia commented on src/data/CCBV.ml
> +let[@inline] mod_ n = (n lsl (Sys.word_size - 4)) lsr (Sys.word_size - 4)
I think OCaml (at least `ocamlopt`) is smart enough to optimize away `n * 8` and `n mod 8`. If so, maybe we do not need to sacrifice readability.

2021-05-23 00:28 UTC, c-cube commented on src/data/CCBV.ml
> +let[@inline] mod_ n = (n lsl (Sys.word_size - 4)) lsr (Sys.word_size - 4)
I think the bit shifts are readable, and they will be fast even in bytecode. Other portions of the code need bit twiddling anyway so we could be uniform.

2021-05-24 15:18 UTC, favonia commented on src/data/CCBV.ml
> +      if get_ bv.b i <> 0 then raise Exit
`unsafe_get_` should be okay?

2021-05-24 15:22 UTC, favonia commented on src/data/CCBV.ml
> +      Bytes.unsafe_set b (n-1) (Char.unsafe_chr (lsb_masks_ r));
I wonder if you meant to use `unsafe_set_` here.

2021-05-24 15:30 UTC, favonia commented
I wonder if it's possible to promote `__to_word_l` to be part of the official interface. It has a reasonable semantics modulo bit-endianness. I have been wishing for a function like this to implement hashing and other things. :-)

2021-05-24 15:37 UTC, favonia commented on src/data/CCBV.ml
> +      n := !n + count_bits_ (get_ bv.b i) (* MSB of last element are all 0 *)
Same here (`unsafe_get_`).

2021-05-24 15:51 UTC, favonia commented
PS: I am not sure how "unsafe" we want to be, but there are also `Bytes.unsafe_blit` and `Bytes.unsafe_fill` to exploit.

2021-05-24 15:55 UTC, c-cube commented
> I wonder if it's possible to promote `__to_word_l` to be part of the official interface. With bytes, it has a reasonable semantics modulo bit-endianness. I have been wishing for a function like this to implement hashing and efficient serialization. :-)

The interplay with `size` (or lack thereof, if we move in that direction indeed) seems non-trivial to me, at least for hashing. For serialization I think it's fine if there's also a reverse function. Maybe in a submodule dedicated to conversion with lists/seqs of bytes?

Btw @favonia do you happen to be on IRC? sometimes it's nice to talk live :-) (on #ocaml on libera.chat).

2021-05-25 02:36 UTC, favonia commented
> The interplay with `size` (or lack thereof, if we move in that direction indeed) seems non-trivial to me, at least for hashing. For serialization I think it's fine if there's also a reverse function. Maybe in a submodule dedicated to conversion with lists/seqs of bytes?

Got it. Perhaps all of these belong to another PR, then.

2021-05-25 04:08 UTC, c-cube commented
> Got it. Perhaps all of these belong to another PR, then.

They do, please keep them coming :slightly_smiling_face:

2021-05-27 18:52 UTC, copy commented
I believe most functions in this would be faster if they operated on 64 bits at a time (or 32 bits for 32-bit platforms and jsoo). Unsafe operations are available as primitives (`external get_int{32,64}_unsafe : string -> int -> int{32,64} = "%caml_bytes_get{32,64}u"`).

2021-05-27 19:31 UTC, c-cube commented
@copy isn't there some overhead to using these externals? Are they unboxed? I'd want to see benchmarks first :slightly_smiling_face: .

Also they're >= 4.08 only.

2021-05-27 20:20 UTC, copy commented
> @copy isn't there some overhead to using these externals? Are they unboxed? I'd want to see benchmarks first.

Yes, they are unboxed (even without flambda): https://godbolt.org/z/z4vMjK6h4

As for performance, on 4.12.0+flambda:

```
┌──────────┬──────────┐
│ Name     │ Time/Run │
├──────────┼──────────┤
│ negate8  │  43.83ns │
│ negate64 │   7.46ns │
└──────────┴──────────┘
```

```ocaml
let[@inline] unsafe_get_ b i = Char.code (Bytes.unsafe_get b i)
let[@inline] unsafe_set_ b i v = Bytes.unsafe_set b i (Char.unsafe_chr v)

let negate8 b =
  for i = 0 to Bytes.length b - 1 do
    unsafe_set_ b i (lnot (unsafe_get_ b i))
  done

external get_int64_unsafe : bytes -> int -> int64 = "%caml_bytes_get64u"
external set_int64_unsafe : bytes -> int -> int64 -> unit = "%caml_bytes_set64u"

let negate64 b =
    for i = 0 to Bytes.length b / 8 - 1 do
        let i = i * 8 in
        set_int64_unsafe b i (Int64.lognot (get_int64_unsafe b i))
    done

open Core_bench
let () =
  let xs = Bytes.create 64 in
  Bench.bench [
    Bench.Test.create ~name:"negate8" (fun () ->
        negate8 xs
      );
    Bench.Test.create ~name:"negate64" (fun () ->
        negate64 xs
      );
  ]
```

2021-05-27 20:20 UTC, Gbury commented
As far as I can tell, the `Bytes.get_X ` functions are actually compiler primitive (e.g. `caml_bytes_get32`) and are compiled to loads from memory (with or without bound checks depending on whether it is `unsafe`), so there should be no real overhead, ^^

2021-05-27 20:21 UTC, c-cube commented
Sure, but since they're not aligned it's probably going to do a shift+`lor` to reconstruct the integer in the first place? Not sure why that should be faster.

2021-05-27 20:23 UTC, Gbury commented
> Sure, but since they're not aligned it's probably going to do a shift+`lor` to reconstruct the integer in the first place? Not sure why that should be faster.

That depends on whether the architecture supports unaligned (as in, aligned on words) loads or not: if the arch supports unaligned loads, then it is a single load, else, there is some reconstruction involved indeed.
For reference  `amd64` (e.g. `x86_64`) allows unaligned loads.

2021-05-27 20:26 UTC, c-cube commented
Ok, I stand corrected. @copy you need to process the last (up to) 7 bytes in your benchmark though :)

2021-05-27 20:27 UTC, Gbury commented
Small note: In the godbolt link, most of the instructions of the `set_` function actually seem to be from the bound check (you can see the `movq    -8(%rax), %rsi` reading the header of the bytes passed as argument, and then the computation of the actual bytes length in number of bytes that goes on basically until the jump). Not sure that it actually affects performances as processors nowadays are pretty good at guessing that bounds check do not raise most of the time, ^^

2021-05-27 20:32 UTC, c-cube commented
I'm pretty impressed by this, @copy . Thanks for the suggestion, it could be worth it. I don't think we have a way, sadly, to special case jsoo (as it's compiled for 64 bits bytecode).

This would bump the minimal version of OCaml to 4.08. Maybe it's time to finally do that; these `bytes` operators have been in my sights for a while :slightly_smiling_face: .

2021-05-27 21:01 UTC, copy commented
> Small note: In the godbolt link, most of the instructions of the set_ function actually seem to be from the bound check (you can see the movq -8(%rax), %rsi reading the header of the bytes passed as argument, and then the computation of the actual bytes length in number of bytes that goes on basically until the jump).

Are you sure? The `u` in `caml_bytes_get64u` stands for unsafe, I don't think it should do bounds checking. I also don't see any exceptions in the code.

> This would bump the minimal version of OCaml to 4.08. Maybe it's time to finally do that; these bytes operators have been in my sights for a while 

They were introduced in https://github.com/ocaml/ocaml/commit/4c704c9e296189c65cfc421f6fe4d3de37242de0, so 4.07.0 apparently. In older versions you could use `%caml_string_set64u`.

2021-05-27 21:13 UTC, c-cube commented
The `@since ` annotations indicate 4.08. The external didn't exist before, did it?

2021-05-27 21:27 UTC, copy commented
> The @since annotations indicate 4.08. The external didn't exist before, did it?

The external was added in 4.07 (in the commit I linked above), and previously existed under a different name.

2021-05-27 21:31 UTC, Gbury commented
> > .
> 
> Are you sure? The `u` in `caml_bytes_get64u` stands for unsafe, I don't think it should do bounds checking. I also don't see any exceptions in the code.
> 
> >

Yes you're correct, my comment was about the `set_` function defined at line 4 in your example, and indeed in the rest whenever you use the unsafe version, there are no bound checks as expected (so in a nutshell my comment was rather useless, ^^).

2021-05-28 00:01 UTC, favonia commented
Wow this is all very exciting. I wonder if we should set up some benchmark before this PR to experiment all kinds of interesting implementations. (I am very curious about whether this PR is faster than the current CCBV.)

2021-06-02 23:32 UTC, c-cube commented
What's the status on that PR, @FardaleM ? :slightly_smiling_face:

2021-06-03 08:23 UTC, FardaleM commented
I plan to add benchmarks with the different ideas but currently I don't have much time to do that.

2022-01-25 17:26 UTC, c-cube commented
closed in favor of #394, if there's benchmarks they should be added there :)

2022-01-25 17:26 UTC, closed without merging